import Head from "next/head";
import Image from "next/image";
import ContactSection from "../components/ContactSection";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import QuoteSection from "../components/QuoteSection";
import TeamSection from "../components/TeamSection";
import ThirdSection from "../components/ThirdSection";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Chemotronix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main>
        <Navbar />
        <Hero />
        <QuoteSection />
        <ThirdSection />
        <TeamSection />
        <ContactSection />
        <footer className="bg-[#E9F4FB] flex items-center justify-center py-6">
          <p>Copyright ©2022. All right reserved | Chemotronix</p>
        </footer>
      </main>
    </div>
  );
}
