import Head from "next/head";
import Image from "next/image";
import ContactSection from "../components/ContactSection";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import QuoteSection from "../components/QuoteSection";
import TeamSection from "../components/TeamSection";
import ThirdSection from "../components/ThirdSection";
import DefaultLayout from "../layouts/DefaultLayout";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Chemotronix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <DefaultLayout>
      <main
        className="overflow-x-hidden bg-transparent text-black"
        data-theme="emerald"
      >
          <Hero />
          <QuoteSection />
          <ThirdSection />
          <TeamSection />
          <ContactSection />
      </main>
      </DefaultLayout>
    </div>
  );
}
